### ISSUE TITLE
你好，请问在运行训练文件时，在hydra部分出现问题应该如何解决

### ISSUE THREAD

**Issue by Summerxu86** [yahuiliu99/PointConT#1]
![Z1YA}${%S3H2V 9QG8HPA M](https://github.com/yahuiliu99/PointConT/assets/105544339/8dfda844-5042-4dc5-8872-90de8916652f)
你好，我在运行时出现以上错误，应该如何解决呢？谢谢！期待您尽快回复！

**Comment by yahuiliu99** [comment]
您好，请确认下安装的hydra版本是否为1.1 ( pip show hydra-core)
如果不是，请安装1.1版本 (pip install hydra-core==1.1)
希望能解决您的问题~
